ALTER TABLE "Rider"
  ADD COLUMN "serviceAreas" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "dailyCapacity" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN "availability" TEXT NOT NULL DEFAULT 'AVAILABLE';
